import React, { CSSProperties, FormEvent, KeyboardEvent, useEffect, useRef, useState } from 'react';
import { Bot, Image as ImageIcon, Mic, Paperclip, Plus, Send, ShieldCheck, Square, Trash2, X } from 'lucide-react';
import { crmFetch } from '../lib/crmApi';

type Attachment = { kind: 'image' | 'audio'; name: string; mimeType: string; dataUrl: string; duration?: number };
type ChatMessage = { id: string; role: 'user' | 'assistant'; text: string; tool?: string | null; status?: string; attachment?: Omit<Attachment, 'dataUrl'> & { previewUrl?: string } };
const THREAD_STORAGE_KEY = 'ybcrm_internal_ai_thread';
const QUICK_PROMPTS = ['Что сегодня произошло в бизнесе?', 'Покажи продажи за сегодня', 'Какие остатки на складе?', 'Статус производства'];
const TOOL_LABELS: Record<string, string> = { get_customer: 'Карточка клиента', search_customers: 'Поиск клиентов', get_order: 'Карточка заказа', search_orders: 'Поиск заказов', get_sales_summary: 'Продажи', get_payments: 'Платежи', get_inventory: 'Склад', get_production_status: 'Производство', get_finance_summary: 'Финансы', get_tasks: 'Задачи', get_supplier: 'Поставщики', search_communications: 'Коммуникации' };
async function responsePayload(response: Response) { return response.json().catch(() => ({})); }
function fileToDataUrl(file: Blob) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result || '')); reader.onerror = reject; reader.readAsDataURL(file); }); }
function timeLabel(seconds = 0) { const value = Math.max(0, Math.round(seconds)); return `${Math.floor(value / 60)}:${String(value % 60).padStart(2, '0')}`; }

export default function InternalAIChatPage() {
  const [threadId, setThreadId] = useState(() => window.localStorage.getItem(THREAD_STORAGE_KEY) || '');
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState(''); const [attachment, setAttachment] = useState<Attachment | null>(null);
  const [loading, setLoading] = useState(false); const [historyLoading, setHistoryLoading] = useState(Boolean(threadId)); const [error, setError] = useState('');
  const [recordingSeconds, setRecordingSeconds] = useState(0); const [isRecording, setIsRecording] = useState(false);
  const [mobileViewportHeight, setMobileViewportHeight] = useState<number | null>(null);
  const endRef = useRef<HTMLDivElement>(null); const fileRef = useRef<HTMLInputElement>(null); const recorderRef = useRef<MediaRecorder | null>(null); const streamRef = useRef<MediaStream | null>(null); const chunksRef = useRef<Blob[]>([]); const timerRef = useRef<number | null>(null); const recordingSecondsRef = useRef(0);

  useEffect(() => { if (!threadId) return; let active = true; void (async () => { try { const response = await crmFetch(`/api/ai-chat/${encodeURIComponent(threadId)}/messages`); const payload = await responsePayload(response); if (response.status === 404) { window.localStorage.removeItem(THREAD_STORAGE_KEY); if (active) { setThreadId(''); setMessages([]); } return; } if (!response.ok) throw new Error(payload.error || 'Не удалось загрузить диалог'); if (active) setMessages(Array.isArray(payload) ? payload : []); } catch (cause) { if (active) setError(cause instanceof Error ? cause.message : 'Не удалось загрузить диалог'); } finally { if (active) setHistoryLoading(false); } })(); return () => { active = false; }; }, [threadId]);
  useEffect(() => { endRef.current?.scrollIntoView({ behavior: 'smooth', block: 'nearest' }); }, [messages, loading]);
  useEffect(() => () => { streamRef.current?.getTracks().forEach(track => track.stop()); if (timerRef.current) window.clearInterval(timerRef.current); }, []);
  useEffect(() => {
    const viewport = window.visualViewport;
    if (!viewport) return;
    const updateViewport = () => setMobileViewportHeight(viewport.height + Math.min(viewport.offsetTop, 56) - 56);
    updateViewport();
    viewport.addEventListener('resize', updateViewport);
    viewport.addEventListener('scroll', updateViewport);
    return () => { viewport.removeEventListener('resize', updateViewport); viewport.removeEventListener('scroll', updateViewport); };
  }, []);

  const startNewChat = () => { window.localStorage.removeItem(THREAD_STORAGE_KEY); setThreadId(''); setMessages([]); setInput(''); setAttachment(null); setError(''); setHistoryLoading(false); };
  const selectImage = async (file?: File) => { if (!file) return; if (!['image/jpeg', 'image/png', 'image/webp', 'image/gif'].includes(file.type) || file.size > 5_000_000) { setError('Можно приложить JPG, PNG, WEBP или GIF размером до 5 МБ'); return; } setAttachment({ kind: 'image', name: file.name, mimeType: file.type, dataUrl: await fileToDataUrl(file) }); setError(''); };
  const clearRecordingTimer = () => { if (timerRef.current) window.clearInterval(timerRef.current); timerRef.current = null; };
  const startRecording = async () => { try { if (!navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === 'undefined') throw new Error('unsupported'); const stream = await navigator.mediaDevices.getUserMedia({ audio: { echoCancellation: true, noiseSuppression: true } }); const candidates = ['audio/mp4', 'audio/webm;codecs=opus', 'audio/webm']; const preferred = candidates.find(type => MediaRecorder.isTypeSupported(type)); const recorder = preferred ? new MediaRecorder(stream, { mimeType: preferred }) : new MediaRecorder(stream); streamRef.current = stream; recorderRef.current = recorder; chunksRef.current = []; recordingSecondsRef.current = 0; setRecordingSeconds(0); setIsRecording(true); setAttachment(null); setError(''); recorder.ondataavailable = event => { if (event.data.size) chunksRef.current.push(event.data); }; recorder.onerror = () => { clearRecordingTimer(); stream.getTracks().forEach(track => track.stop()); setIsRecording(false); setError('Запись прервалась. Попробуйте ещё раз.'); }; recorder.onstop = async () => { const mimeType = recorder.mimeType.split(';')[0] || preferred || 'audio/webm'; const blob = new Blob(chunksRef.current, { type: mimeType }); stream.getTracks().forEach(track => track.stop()); streamRef.current = null; if (!blob.size || recordingSecondsRef.current < 1) setError('Запись слишком короткая. Удерживайте запись хотя бы секунду.'); else if (blob.size > 6_000_000) setError('Голосовое сообщение слишком большое. Запишите короче.'); else setAttachment({ kind: 'audio', name: `voice-${Date.now()}.${mimeType.includes('mp4') ? 'm4a' : 'webm'}`, mimeType, dataUrl: await fileToDataUrl(blob), duration: recordingSecondsRef.current }); }; recorder.start(250); timerRef.current = window.setInterval(() => { recordingSecondsRef.current += 1; setRecordingSeconds(recordingSecondsRef.current); if (recordingSecondsRef.current >= 120) stopRecording(); }, 1000); } catch { streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; setIsRecording(false); setError('Не удалось включить микрофон. Разрешите доступ в настройках браузера.'); } };
  const stopRecording = () => { clearRecordingTimer(); const recorder = recorderRef.current; recorderRef.current = null; if (recorder?.state === 'recording') recorder.stop(); setIsRecording(false); };
  const cancelRecording = () => { clearRecordingTimer(); chunksRef.current = []; recordingSecondsRef.current = 0; const recorder = recorderRef.current; recorderRef.current = null; if (recorder?.state === 'recording') recorder.stop(); streamRef.current?.getTracks().forEach(track => track.stop()); streamRef.current = null; setIsRecording(false); setRecordingSeconds(0); };

  const send = async (text = input) => { const clean = text.trim(); if ((!clean && !attachment) || loading || isRecording) return; const currentAttachment = attachment; const optimistic: ChatMessage = { id: `local-${Date.now()}`, role: 'user', text: clean || (currentAttachment?.kind === 'audio' ? 'Голосовое сообщение' : 'Фотография'), attachment: currentAttachment ? { kind: currentAttachment.kind, name: currentAttachment.name, mimeType: currentAttachment.mimeType, duration: currentAttachment.duration, previewUrl: currentAttachment.dataUrl } : undefined }; setMessages(current => [...current, optimistic]); setInput(''); setAttachment(null); setError(''); setLoading(true); try { const response = await crmFetch('/api/ai-chat/message', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: clean, attachment: currentAttachment, ...(threadId ? { threadId } : {}) }) }); const payload = await responsePayload(response); if (payload.threadId && payload.threadId !== threadId) { setThreadId(payload.threadId); window.localStorage.setItem(THREAD_STORAGE_KEY, payload.threadId); } if (!response.ok) throw new Error(payload.error || 'AI-чат временно недоступен'); setMessages(current => [...current, payload.message]); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Не удалось получить ответ'); } finally { setLoading(false); } };
  const submit = (event: FormEvent) => { event.preventDefault(); void send(); }; const handleKeyDown = (event: KeyboardEvent<HTMLTextAreaElement>) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); void send(); } };

  const mobileStyle = mobileViewportHeight ? ({ '--ai-chat-mobile-height': `${Math.max(320, mobileViewportHeight)}px` } as CSSProperties) : undefined;

  return <div style={mobileStyle} className="fixed inset-x-0 top-14 z-[90] mx-auto flex h-[var(--ai-chat-mobile-height,calc(100dvh-56px))] max-w-4xl flex-col overflow-hidden bg-[#dce7ef] sm:static sm:mt-4 sm:h-[calc(100dvh-180px)] sm:min-h-[620px] sm:rounded-2xl sm:border sm:border-slate-200 sm:shadow-xl">
    <header className="z-10 flex min-h-[58px] items-center justify-between border-b border-slate-200/80 bg-white/95 px-3 py-2 backdrop-blur sm:px-4"><div className="flex min-w-0 items-center gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-gradient-to-br from-[#7D7DE6] to-[#5b67d9] text-white"><Bot size={21}/></div><div className="min-w-0"><h2 className="truncate text-[15px] font-semibold text-slate-900">AI-помощник CRM</h2><div className="flex items-center gap-1.5 text-[12px] text-emerald-600"><span className="h-2 w-2 rounded-full bg-emerald-500"/>OpenAI GPT · только чтение</div></div></div><button onClick={startNewChat} className="flex h-10 items-center gap-1.5 rounded-full px-3 text-sm font-medium text-[#6574d8] hover:bg-indigo-50" aria-label="Начать новый диалог"><Plus size={18}/><span className="hidden sm:inline">Новый чат</span></button></header>
    <section aria-label="Диалог с AI" aria-live="polite" className="relative min-h-0 flex-1 overscroll-contain overflow-y-auto bg-[radial-gradient(circle_at_1px_1px,rgba(100,116,139,0.12)_1px,transparent_0)] bg-[size:22px_22px] px-2 py-4 [-webkit-overflow-scrolling:touch] sm:px-5">
      {historyLoading ? <div className="flex h-full items-center justify-center text-sm text-slate-500">Загружаем диалог…</div> : messages.length === 0 ? <div className="mx-auto flex h-full max-w-lg flex-col items-center justify-center text-center"><div className="rounded-2xl bg-white/90 p-5 shadow-sm"><Bot className="mx-auto text-[#6976df]" size={34}/><h3 className="mt-3 font-semibold">Чем помочь?</h3><p className="mt-1 text-sm text-slate-500">Можно написать, записать голосовое или приложить фотографию.</p></div><div className="mt-4 grid w-full grid-cols-2 gap-2">{QUICK_PROMPTS.map(prompt => <button key={prompt} onClick={() => void send(prompt)} className="rounded-2xl bg-white/90 px-3 py-3 text-left text-[13px] shadow-sm hover:bg-white">{prompt}</button>)}</div></div> : <div className="space-y-2">{messages.map(message => <article key={message.id} className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[88%] rounded-[18px] px-3.5 py-2 text-[15px] leading-[1.45] shadow-sm sm:max-w-[76%] ${message.role === 'user' ? 'rounded-br-[5px] bg-[#dcd7ff] text-slate-900' : message.status === 'error' ? 'rounded-bl-[5px] border border-red-200 bg-red-50 text-red-800' : 'rounded-bl-[5px] bg-white text-slate-800'}`}>{message.attachment?.kind === 'image' && message.attachment.previewUrl && <img src={message.attachment.previewUrl} alt={message.attachment.name} className="mb-2 max-h-72 w-full rounded-xl object-cover"/>}{message.attachment?.kind === 'audio' && <div className="mb-1 flex items-center gap-2 rounded-xl bg-white/55 px-2 py-2"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-[#7166d9] text-white"><Mic size={17}/></span><span className="tracking-[3px] text-[#7166d9]">▮▯▮▮▯▮▯▮▮▯</span><span className="text-xs text-slate-500">{timeLabel(message.attachment.duration)}</span></div>}<div className="whitespace-pre-wrap break-words">{message.text}</div>{message.tool && <div className="mt-1.5 text-[10px] font-semibold uppercase tracking-wide text-[#7166d9]">{TOOL_LABELS[message.tool] || message.tool}</div>}</div></article>)}{loading && <div className="flex justify-start"><div className="rounded-[18px] rounded-bl-[5px] bg-white px-4 py-2.5 text-sm text-slate-500 shadow-sm"><span className="animate-pulse">Проверяю данные CRM…</span></div></div>}<div ref={endRef}/></div>}
    </section>
    <div className="shrink-0 border-t border-slate-200 bg-white/95 px-2 pb-[max(8px,env(safe-area-inset-bottom))] pt-2 backdrop-blur sm:px-3">
      {error && <div role="alert" className="mb-2 flex items-center justify-between gap-2 rounded-xl bg-red-50 px-3 py-2 text-xs text-red-700"><span>{error}</span><button onClick={() => setError('')} className="h-9 w-9 shrink-0 rounded-full" aria-label="Закрыть ошибку"><X className="mx-auto" size={16}/></button></div>}
      {attachment && <div className="mb-2 flex items-center gap-2 rounded-xl bg-slate-100 p-2">{attachment.kind === 'image' ? <img src={attachment.dataUrl} alt="Предпросмотр" className="h-12 w-12 rounded-lg object-cover"/> : <audio src={attachment.dataUrl} controls preload="metadata" className="h-10 min-w-0 flex-1" aria-label="Прослушать голосовое сообщение"/>}{attachment.kind === 'image' && <div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{attachment.name}</div><div className="text-xs text-slate-500">Фото готово к отправке</div></div>}<button onClick={() => setAttachment(null)} className="h-10 w-10 shrink-0 rounded-full hover:bg-slate-200" aria-label="Убрать вложение"><X className="mx-auto" size={18}/></button></div>}
      {isRecording ? <div className="flex min-h-12 items-center gap-2 rounded-full bg-red-50 px-2"><button onClick={cancelRecording} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full text-red-500 hover:bg-red-100" aria-label="Удалить запись"><Trash2 size={18}/></button><span className="h-3 w-3 animate-pulse rounded-full bg-red-500"/><span className="flex-1 text-sm font-medium text-red-700">Запись {timeLabel(recordingSeconds)}</span><button onClick={stopRecording} className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-red-500 text-white" aria-label="Остановить запись"><Square size={16} fill="currentColor"/></button></div> : <form onSubmit={submit} className="flex items-end gap-1.5"><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif" className="hidden" onChange={event => { void selectImage(event.target.files?.[0]); event.currentTarget.value = ''; }}/><button type="button" onClick={() => fileRef.current?.click()} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full text-[#6574d8] hover:bg-indigo-50" aria-label="Приложить фотографию"><Paperclip size={23}/></button><div className="flex min-h-11 min-w-0 flex-1 items-end rounded-[22px] border border-slate-200 bg-slate-50 px-3 focus-within:border-[#7D7DE6] focus-within:bg-white"><label className="sr-only" htmlFor="ai-chat-message">Сообщение AI-помощнику</label><textarea id="ai-chat-message" rows={1} maxLength={2000} value={input} onChange={event => setInput(event.target.value)} onKeyDown={handleKeyDown} disabled={loading} placeholder="Сообщение" className="max-h-28 min-h-[42px] min-w-0 flex-1 resize-none bg-transparent py-[10px] text-base leading-6 outline-none disabled:opacity-60"/><button type="button" onClick={() => fileRef.current?.click()} className="mb-1 hidden h-9 w-9 shrink-0 items-center justify-center rounded-full text-slate-400 hover:text-[#6574d8] min-[380px]:flex" aria-label="Выбрать изображение"><ImageIcon size={20}/></button></div>{input.trim() || attachment ? <button type="submit" disabled={loading} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[#6574d8] text-white disabled:opacity-40" aria-label="Отправить"><Send size={19}/></button> : <button type="button" onClick={() => void startRecording()} className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-[#6574d8] text-white" aria-label="Записать голосовое сообщение"><Mic size={21}/></button>}</form>}
      <div className="mt-1 flex items-center justify-center gap-1 text-[10px] text-slate-400"><ShieldCheck size={11}/>AI только читает данные CRM</div>
    </div>
  </div>;
}
